### ISSUE TITLE
Takes ages to install

### ISSUE THREAD

**Issue by gaku-sei** [Astrocoders/lenses-ppx#11]
On my laptop, with a decent internet connection speed, installation takes up to 25 minutes, and sometimes fails (with `npm`, it seems it works with `yarn`).

Most of the installation time is due to `bsb-native` takings ages to download.

I assume `bsb-native` is used to build `ppx-lense`, but it seems it's not a viable solution. Would you consider releasing on npm the compiled binaries instead?

**Comment by fakenickels** [comment]
`bsb-native` really takes a long time to build
releasing pre-built binaries looks like a good alternative, do you know any setup of this already working that we could base ourselves on?

also, we actually intended to move to Esy (https://github.com/Astrocoders/lenses-ppx/issues/9) and use it to release the binaries

**Comment by gaku-sei** [comment]
A pretty common approach would be to host the binaries on a server, and just download the needed version on npm install (requires an extra server).

Also, I know Elm used to use [binwrap](https://www.npmjs.com/package/binwrap) for a while. They changed last month, and the binary is now version controlled ([here](https://github.com/elm/compiler/tree/master/installers/npm/bin)). Could be a good alternative, since you don't need to host the binaries yourself.

**Comment by fakenickels** [comment]
Already rewrote with esy, now just missing to set up the pipeline to distribute the binaries.

**Comment by fakenickels** [comment]
Solved at v4.0.0
