### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by romanschejbal** [Astrocoders/lenses-ppx#13]
As far as I understand the configured workflow, it does not build a binary for Windows. We do have a team member with a Windows laptop thus we need to support that platform. I'm happy to help set this up (although I'm very new to the Github Actions) or test. Thanks!

**Comment by fakenickels** [comment]
Hey there!
Sorry about not having provided the Windows binary, I think I ran into some problems while setting it up and ended up forgetting to try back.

But a good place to start if you want to try out is to add Windows to the matrix 
https://github.com/Astrocoders/lenses-ppx/blob/master/.github/workflows/pipeline.yml#L15
