### ISSUE TITLE
Fail to run demo

### ISSUE THREAD

**Issue by timerg** [Astrocoders/lenses-ppx#23]
What I have done:
- run `esy` in `/packages` 
- run `yarn install` in demo
- spin up  bs platform by `yarn run watch`

and the bs compiler complained: `Fatal error: exception Failure("Ast_mapper: OCaml version mismatch or malformed input")`

**Comment by timerg** [comment]
After more research, I found that bs-platform is using ocaml 4.06. But this project [update to 4.09](dbdebe6d0384f70799675573bfcf2581692ffdff). Is that means the latest version doesn't support for usage  by bucklescript?

**Comment by fakenickels** [comment]
Hey there @timerg! Thanks for trying to contribute

The problem happened because I merged too prematurely a upgrade and clean up PR, I just reverted it in master so you can probably run it now https://github.com/Astrocoders/lenses-ppx/pull/25

I'll properly finish the upgrade when I'm able

**Comment by timerg** [comment]
Thanks!
