### ISSUE TITLE
[Help] GLIBC_2.27 not found

### ISSUE THREAD

**Issue by DCKT** [Astrocoders/lenses-ppx#30]
Hello,

I upgrade to the latest version of lenses-ppx and everything works fine except on the Gitlab CI, I got this error : 
```
/node_modules/lenses-ppx/ppx: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found
```
I'm using `node:lts`

Is this esy related ?

Thanks

**Comment by mattbeedle** [comment]
Debian Buster uses 2.27. You can fix by switching your docker image to `node:lts-buster`

**Comment by fakenickels** [comment]
It appears to be related to this issue https://github.com/esy/esy/issues/1190

**Comment by LeoLeBras** [comment]
We use Netlify to deploy our app and it is now blocking to update to version `6.x.x`.

**Comment by fakenickels** [comment]
I tried to build the project with esy@nightly but it did not work still. We have the same problem and as a temp solution we are now deploying to netlify using the CLI directly from our pipeline. I'm yet to provide a reproduction demo https://github.com/esy/esy/issues/1190#issuecomment-758067689

**Comment by DCKT** [comment]
I can confirm, using `node:lts-buster` fix the issue
