### ISSUE TITLE
Use esy

### ISSUE THREAD

**Issue by fakenickels** [Astrocoders/lenses-ppx#9]

**Comment by baransu** [comment]
[minima-app/bs-log](https://github.com/minima-app/bs-log) recently switched from `bsb-native` to `esy` so it would be a good example of a transition and es setup for ppx

**Comment by fakenickels** [comment]
that's a really good reference, thanks @baransu!

**Comment by fakenickels** [comment]
Done, just missing to set the pipeline to distribute the binaries
